apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: elastic-stack
  namespace: flux-system
namespace: flux-system
resources:
  - ./clusters/iot-elk-cluster/elasticsearch-cluster     
  - ./clusters/iot-elk-cluster/elastic-operator
  - ./clusters/iot-elk-cluster/flux-system