---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-operator-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path:  ./clusters/iot-elk-cluster/elastic-operator-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elasticsearch-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path:  ./clusters/iot-elk-cluster/elasticsearch-kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: elastic-operator-kustomization
