apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-stack
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/iot-elk-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: flux-system
  resources:
    - ./clusters/iot-elk-cluster/elasticsearch-cluster     
    - ./clusters/iot-elk-cluster/elastic-operator  