apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: elastic-stack
  namespace: flux-system
namespace: flux-system
resources:
  - ./elasticsearch-cluster
  - ./elastic-operator
  - ./flux-system