apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: iot-elk-cluster
  namespace: flux-system
spec:
  interval: 1m
  path: ./elk-clusters/iot-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
