apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  releaseName: elastic-operator
  chart:
    spec:
      chart: elastic/eck-operator
      version: 2.16 # Replace with the desired version
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  interval: 5m
  values:
    managedNamespaces:
      - elastic-cluster
