---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: esaas-kb-backend
  namespace: elasticsearch-cluster
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600
