apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: client02-elk-cluster
  namespace: client02-gitops
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/elasticsearch
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    # Elasticsearch Configuration
    elasticsearch:
      clusterName: "iot-cluster"
      version: "8.17.1"
      replicas: 3
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "800m"

    # Kibana Configuration
    kibana:
      enabled: true
      version: "8.17.1"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"

    # Logstash Configuration
    logstash:
      enabled: false
      version: "8.17.1"
      replicas: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"

